<a href="https://colab.research.google.com/github/AgnieszkaBorys/data-science-bootcamp/blob/master/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print('Hello COlab!')

Hello COlab!


In [2]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
print(dir(np))

In [0]:
help(np.array)

PODSTAWY

1D ARRAY

In [0]:
x = np.array([1, 3])
x

array([1, 3])

In [0]:
print(x)

[1 3]


In [0]:
type(x)

numpy.ndarray

In [0]:
x.ndim

1

In [0]:
x.shape

(2,)

In [0]:
x.size


2

In [0]:
x.dtype

dtype('int64')

2D ARRAY

In [0]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [0]:
x.dtype

dtype('float64')

In [0]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [0]:
x.ndim

2

In [0]:
x.shape

(2, 2)

In [0]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [0]:
x.shape

(2, 3)

3D ARRAY

In [0]:
x = np.array(
    [[[4, 3, 1],
      [3, 2, 1]],
     
     [[4 ,1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [0]:
x.ndim

3

In [0]:
x.shape

(3, 2, 3)

TYPY DANYCH

In [0]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [0]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [0]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [0]:
A = np.array([1, 2, 3], dtype = 'complex')
A.dtype

dtype('complex128')

In [0]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [0]:
A = np.array([1.0, 2.7, 3.3], dtype = 'int')
A.dtype

dtype('int64')

In [0]:
A

array([1, 2, 3])

In [0]:
A = np.array([True, False])
A.dtype

dtype('bool')

Typ danych skrocony integer

In [0]:
A = np.array([24, 120, 230], dtype = np.int8)
A.dtype

dtype('int8')

Typ danych do zapisywania pikseli obrazka - od 0 do 250

In [0]:
A = np.array([24, 120, 230], dtype = np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [4]:
np.zeros(shape = (4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [14]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [15]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [0]:
A = np.arange(15)

In [19]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
A.reshape(5, -1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [23]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [24]:
A + B

array([6, 0, 7, 4])

In [25]:
A - B

array([0, 2, 1, 0])

In [26]:
A * B

array([ 9, -1, 12,  4])

In [27]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [33]:
np.add(A, B)

array([6, 0, 7, 4])

In [34]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [35]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [36]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [28]:
A + 3

array([6, 4, 7, 5])

In [29]:
2 * A

array([6, 2, 8, 4])

In [30]:
abs(B)

array([3, 1, 3, 2])

In [31]:
A + 3*B

array([12, -2, 13,  8])

Mnożenie macierzy

In [39]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


Można pomnożyć element * element macierzy

In [38]:
X * Y

array([[6, 0],
       [2, 0]])

A teraz mnożenie macierzowe

In [40]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [41]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [42]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [43]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

okreżlenie ziarna pozwoli na replikację wyników:

In [0]:
np.random.seed(0)

randn - rozkład normalny (0, 1)

In [45]:
np.random.randn()

1.764052345967664

In [46]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [47]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

rand - rozkład jednostajny na przedizale <0, 1):

In [48]:
np.random.rand()

0.1965823616800535

In [49]:
np.random.rand(10, 2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

randint(n) - losowa liczba calkowita z przediału <0, n):

In [50]:
np.random.randint(10)

1

In [51]:
np.random.randint(low=10, high=101)

60

In [52]:
np.random.randint(low=10, high=101, size=10)

array([37, 24, 51, 68, 75, 46, 20, 96, 53, 21])

metoda choice zwraca losowy element z podanej listy:

In [54]:
np.random.choice([4, 2, 1, 3, 5])

3

In [55]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [57]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Metoda shuffle służy do przetasowania danych (losowa zamiana kolejności). Jest wykonywane bezpośrednio na tabeli.

In [59]:
np.random.shuffle(data)
data

array([2, 1, 4, 9, 8, 5, 7, 3, 0, 6])

Podstawowe funkcje 

In [60]:
np.exp(1)

2.718281828459045

In [61]:
np.sqrt(9)

3.0

Funkcja 'all' sprawdza czy wszystkie wartości w tabeli są True, a funkcja 'any' czy choć jedna jest True

In [62]:
np.all([2, 3, 1])

True

In [63]:
np.all([2, 3, 0])

False

In [64]:
np.any([0, 0, 0])

False

In [65]:
np.any([0, 3, 0])

True

In [66]:
bool(0)

False

In [69]:
A = np.random.rand(5)
A

array([0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538])

Funkcje argmax, argmin, argsort zwracają indeksy tabeli odpowiadjące odpowiednio max, min i posortowanej wersji tabeli

In [70]:
np.argmax(A)

3

In [71]:
A[np.argmax(A)]

0.952749011516985

In [72]:
np.argmin(A)

2

In [73]:
np.argsort(A)

array([2, 4, 1, 0, 3])

Funkcje max, min, mean, mediam, std zwracają wartości tabeli zaś sort działa na wartościach tabeli i ją zmienia!

In [74]:
np.max(A)

0.952749011516985

In [75]:
np.min(A)

0.2230816326406183

In [76]:
np.mean(A)

0.5574499719675885

In [77]:
np.median(A)

0.5722519057908734

In [78]:
np.std(A)

0.237339728576655

In [79]:
np.sort(A)

array([0.22308163, 0.44712538, 0.57225191, 0.59204193, 0.95274901])

Indeksowanie, Wycinanie

In [80]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [81]:
A[2]

2

In [82]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [83]:
A[:2]

array([0, 1])

In [84]:
A[[0,2]]

array([0, 2])

In [85]:
A[-1]

19

In [86]:
A[10:15]

array([10, 11, 12, 13, 14])

In [89]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
A[0]

array([0, 1, 2, 3, 4])

In [91]:
A[1]

array([5, 6, 7, 8, 9])

In [94]:
A[:, 0]

array([ 0,  5, 10, 15])

In [95]:
A[:, -1]

array([ 4,  9, 14, 19])

In [96]:
A[1, 1]

6

In [97]:
A[1, 3]

8

In [99]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [101]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

ITERACJA PO TABLICACH

In [104]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [105]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


ZMIANA ROZMIARU TABLIC

In [107]:
A.shape

(4, 5)

In [109]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Metoda ravel pozwala na wypłaszczenie tablicy

In [110]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Metoda T  - transpozycja macierzy




In [111]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

MASKI LOGICZNE

In [114]:
A = np.arange(start=-10, stop=10, step = 0.5)
A = A.reshape(10, -1)  #-1 oznacza ze sam dobiera pasujacy wymiar
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [115]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [117]:
np.bitwise_and(A > -5, A < 5)  #umożliwia podanie więcej warunków IF

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [118]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [119]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])