<a href="https://colab.research.google.com/github/AgnieszkaBorys/data-science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__

'1.18.3'

In [6]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [7]:
np.linalg.norm(v1)

4.123105625617661

In [9]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [11]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

5.0

In [12]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

In [19]:
X = np.array([[5,3], 
              [3, 9]])
Y = np.array([[1], 
              [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [20]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [16]:
Z.shape

(2, 1)

In [21]:
X1 = np.array([[2, -1, 3], 
              [3, 1, 0]])
Y1 = np.array([[2, 1, -1], 
              [0, -1, 2],
              [3, 2, 0]])
print(X1, '\n')
print(Y1)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [22]:
np.dot(X1, Y1)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [25]:
X2 = np.array([[-1], [4], [2]])
X2

array([[-1],
       [ 4],
       [ 2]])

In [26]:
np.dot(X1, X2)

array([[0],
       [1]])