<a href="https://colab.research.google.com/github/AgnieszkaBorys/data-science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [0]:
np.linalg.norm(v1)

4.123105625617661

In [0]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [0]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p - q)

5.0

In [0]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p - q)

5.0990195135927845

In [0]:
X = np.array([[5,3], 
              [3, 9]])
Y = np.array([[1], 
              [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [0]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [0]:
Z.shape

(2, 1)

In [0]:
X1 = np.array([[2, -1, 3], 
              [3, 1, 0]])
Y1 = np.array([[2, 1, -1], 
              [0, -1, 2],
              [3, 2, 0]])
print(X1, '\n')
print(Y1)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [0]:
np.dot(X1, Y1)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [0]:
X2 = np.array([[-1], [4], [2]])
X2

array([[-1],
       [ 4],
       [ 2]])

In [0]:
np.dot(X1, X2)

array([[0],
       [1]])

Wyznacznik macierzy

In [3]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10.0

Ślad macierzy

In [4]:
np.trace(A)

5

Macierz jednostkowa

In [5]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [7]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [0]:
np.set_printoptions(precision=4, suppress=True)

In [9]:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [10]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

Transpozycja macierzy

In [12]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [13]:
A.T

array([[ 2, -1],
       [ 4,  3]])

ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ

In [15]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [16]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [18]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]


In [19]:
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]


In [20]:
X.shape

(2, 1)