<a href="https://colab.research.google.com/github/AgnieszkaBorys/data-science-bootcamp/blob/master/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('Hello COlab!')

Hello COlab!


In [3]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
print(dir(np))

In [0]:
help(np.array)

PODSTAWY

1D ARRAY

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size


2

In [12]:
x.dtype

dtype('int64')

2D ARRAY

In [14]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [15]:
x.dtype

dtype('float64')

In [17]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [21]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [22]:
x.shape

(2, 3)

3D ARRAY

In [26]:
x = np.array(
    [[[4, 3, 1],
      [3, 2, 1]],
     
     [[4 ,1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [27]:
x.ndim

3

In [28]:
x.shape

(3, 2, 3)

TYPY DANYCH