<a href="https://colab.research.google.com/github/AgnieszkaBorys/data-science-bootcamp/blob/master/ml2206_02_sn_cyfry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
# komponenty do budowania sieci
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout 
     #flatten umozliwia wypłąszczenie danych zas drpout wyrzuca pewne probki danych z danyh wsadowych w kazdej iteracji aby uniknąć uzaleznienie od danych wsadowych
from tensorflow.keras.datasets.mnist import load_data 

In [24]:
from tensorflow.random import set_seed
set_seed(0)

In [25]:
((X_train, y_train) , (X_test, y_test)) = load_data()

In [26]:
X_train.shape, X_test.shape  #obraz 28 na 28 pikseli w skali szarosci,  0 kolor bialy 255 czarny

((60000, 28, 28), (10000, 28, 28))

In [27]:
np.set_printoptions(linewidth=160)

In [28]:
print(X_train[12])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  12  99  91 142 155 246 182 155 155 155 155 131  52   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 138 254 254 254 254 254 254 254 254 254 254 254 252 210 122  33   0   0   0   0   0   0   0   0   0]
 [  0   0   0 220 254 254 254 235 189 189 189 189 150 189 205 254 254 254  75   0   0   0   0   0   0   0   0   0]
 [  0   0   0  35  74  35  35  25   0   0   0   0   0   0  13 224 254 254 153   

In [29]:
# trick polegający na skalowaniu danych do przedziału (0,1) - to powinno poopprawić wyniki dzialania sieci
# można tez uzuc Skalera ale tutaj jest latweo oliczyc recznie
X_train = X_train/255
X_test = X_test/255

In [30]:
# tworzenie sieci
model = Sequential()
model.add( Flatten(input_shape=(28,28)) )
model.add( Dense(64, activation='relu') )
#model.add( Dense(128, activation='relu') )
model.add( Dense(10, activation='softmax'))  #warstwa wyjsciowa, tutaj 10 wartośi zmiennej y bo identyfikujemy cyfry

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'] )  #typowe wartości dla problemu kategoryzacji (tutaj 10 wartośi zm y bo cyfry)

In [31]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2943 - accuracy: 0.9168
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1444 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1053 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0833 - accuracy: 0.9751
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0690 - accuracy: 0.9797


In [32]:
y_pred = model.predict_classes(X_test)

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
pd.DataFrame(confusion_matrix(y_test, y_pred))

0     1     2    3    4    5    6    7    8    9
0  964     0     2    1    1    1    5    1    3    2
1    0  1120     5    0    0    1    4    0    5    0
2    5     1  1009    2    2    0    1    3    9    0
3    0     0     5  994    1    0    0    4    4    2
4    1     0     1    0  969    0    4    0    2    5
5    2     0     0   20    4  849    5    0    8    4
6    3     3     2    1    6    3  939    0    1    0
7    2     8    11    6    4    0    0  980    1   16
8    1     0     5    4    6    3    2    3  946    4
9    2     4     0    6   12    1    1    3    1  979

# Zapis modelu do pliku

In [35]:
#zwyczajowe rozszerzeie dla plikow z Tensorflow i Keras
model.save('model_cyfry.h5')

In [36]:
#odtworzenie H5 do modelu można to wykorzystać też na innych platformach niż Python
from tensorflow.keras.models import load_model

In [37]:
new_model = load_model('model_cyfry.h5')

In [38]:
type(new_model)

tensorflow.python.keras.engine.sequential.Sequential

In [39]:
y_pred_new = new_model.predict_classes(X_test)

In [40]:
pd.DataFrame( confusion_matrix(y_test, y_pred_new) )

0     1     2    3    4    5    6    7    8    9
0  964     0     2    1    1    1    5    1    3    2
1    0  1120     5    0    0    1    4    0    5    0
2    5     1  1009    2    2    0    1    3    9    0
3    0     0     5  994    1    0    0    4    4    2
4    1     0     1    0  969    0    4    0    2    5
5    2     0     0   20    4  849    5    0    8    4
6    3     3     2    1    6    3  939    0    1    0
7    2     8    11    6    4    0    0  980    1   16
8    1     0     5    4    6    3    2    3  946    4
9    2     4     0    6   12    1    1    3    1  979

Douczanie modelu: jak splywaja kolejne dane historyczne moze dojsc do deprecjacji modelu. Najlepiej dodawac te nowe dane do danych traningowych modelu i puscic model fit jeszcze raz.

